export const tables = {
  users: "users",
  recipes: "recipes",
  likes: "likes",
  bookmarks: "bookmarks",
  comments: "comments",
  recipeTags: "recipe_tags",
  recipeEdits: "recipe_edits",
  recipePolls: "recipe_polls",
  recipePollOptions: "recipe_poll_options",
  recipePollVotes: "recipe_poll_votes",
  recipeCollections: "recipe_collections",
  recipeCollectionItems: "recipe_collection_items",
  notifications: "notifications",
  liveStreams: "live_streams",
  liveComments: "live_comments",
  liveLikes: "live_likes",
  liveViewers: "live_viewers",
  liveModerators: "live_moderators",
  liveBans: "live_bans",
  follows: "follows",
  credentials: "credentials",
  sessions: "sessions",
  authAttempts: "auth_attempts",
} as const;

export type ImageKey = "pumpkin" | "gnocchi" | "baking";
